### ISSUE TITLE
update data service to use new Variable properties

### ISSUE THREAD

**Issue by steve-fischer-200** [VEuPathDB/EdaDataService#49]
for convenience, here is pertinent RAML

```
   API_StringVariable:
    type: API_Variable
    discriminatorValue: string
    properties:
      distinctValuesCount: number
      isTemporal: boolean
      isFeatured: boolean
      isMergeKey: boolean
      isMultiValued: boolean


  API_NumberVariable:
    type: API_Variable
    discriminatorValue: number
    properties:
      units: string
      precision: number
      displayRangeMin?: number
      displayRangeMax?: number
      rangeMin?: number
      rangeMax?: number
      binWidthOverride?: number
      binWidth?: number
      distinctValuesCount: number
      isTemporal: boolean
      isFeatured: boolean
      isMergeKey: boolean
      isMultiValued: boolean

  API_DateVariable:
    type: API_Variable
    discriminatorValue: date
    properties:
      displayRangeMin?: string
      displayRangeMax?: string
      rangeMin?: string
      rangeMax?: string
      binWidthOverride?: string
      binWidth?: string
      distinctValuesCount: number
      isTemporal: boolean
      isFeatured: boolean
      isMergeKey: boolean
      isMultiValued: boolean

  API_LongitudeVariable:
    type: API_Variable
    discriminatorValue: longitude
    properties:
      distinctValuesCount: number
      isTemporal: boolean
      isFeatured: boolean
      isMergeKey: boolean
      isMultiValued: boolean

```
